redis:
  container_name: 'gems_china_redis'
  image: redis:3.2.7-alpine
  mem_limit: 300m
  ports:
    - '6379'
  volumes:
    - ./data/redis:/data

memcached:
  container_name: 'homeland_memcached'
  image: memcached:1.4.31-alpine
  mem_limit: 256m
  ports:
    - '11211'

web:
  container_name: 'gems_china_nginx'
  image: nginx:1.12-alpine
  links:
    - bundler_api
  command: nginx -c /etc/nginx/nginx.conf
  volumes:
    - ./etc/ssl:/etc/ssl
    - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./etc/nginx/html:/etc/nginx/html
    - ./etc/nginx/conf.d/rubygems.conf:/etc/nginx/conf.d/rubygems.conf
    - ./shared/cache/nginx:/var/nginx_cache
    - ./log/nginx:/var/log/nginx
  ports:
    - "80:80"
    - "443:443"

bundler_api:
  container_name: 'gems_china_bundler_api'
  image: rubychina/bundler-api:0.0.1
  links:
    - redis
    - memcached
  ports:
    - '5000'
  volumes:
    - ./log/bundler-api:/var/www/bundler-api/log
  env_file:
    - app.default.env

